version: 1.5.4.{build}
environment:
  my_version: 1.5.4
  my_secret:
    secure: eXAIysIG8npt2tVMYQpGwTLj47CK9lUB/NyEfVGgc90=
skip_branch_with_pr: true
image: Visual Studio 2017
clone_folder: c:\projects\CrashReporter.NET
platform: Any CPU
configuration: Release
install:
- nuget install secure-file -ExcludeVersion

before_build:
- cmd: nuget restore
- secure-file\tools\secure-file -decrypt "c:\projects\CrashReporter.NET\CrashReporter.NET\CrashReporter.NET.snk.enc" -secret %my_secret%

after_build:
- cmd: 7z a CrashReporter.NET-%my_version%.zip %APPVEYOR_BUILD_FOLDER%\CrashReporter.NET\build\lib\net20\*
- nuget pack "c:\projects\CrashReporter.NET\CrashReporter.NET\build\CrashReporter.NET.nuspec"

artifacts:
- path: CrashReporter.NET-%my_version%.zip
- path: CrashReporter.NET.%my_version%.nupkg

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: '// TODO: Write Release Notes'
  artifact: CrashReporter.NET-%my_version%.zip
  auth_token:
    secure: WHW27Nvc8zNhfyhxIYdl/NwbrkFzvSX0vE4/CS8iByPXM6rcztWhUrDXJ7eejLBY
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
    
- provider: NuGet
  api_key:
    secure: f061iyHEh8+Fz3+iV/c+3stBhQuyndcJMP719Eny9w6sbRfMgD1yJe+aVAYW1PJD
  skip_symbols: false
  artifact: CrashReporter.NET.%my_version%.nupkg
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only